---
title: "RWorksheets#2"
author: "Missy Key Sadsad"
date: "2023-09-28"
output: html_document
---
 
<html>
<head>
    <title>R Worksheet for R programming</title>
    <style>
        body {
            font-family: Arial, sans-serif;
         }

        h1 {
             font-size: 15px;
             font-weight: bold;
             font-family: serif;
         }

        h2 {
            font-size: 15px;
            font-family: Georgia, serif;
        }
        
        h3 {
            font-size: 15px;
            font-family: Georgia, serif;
        }
       
        th, td {
        border-bottom: 1px solid black;
        }
  

        
    </style>
</head>
<body>
<h1>1.Create a vector using: Operator</h1>
<h2>a. Sequence from -5 to 5. Write the R code and its output.
    Describe its output.</h2>
```{seq}
seq <- c(-5:5)  
seq
-5 -4 -3 -2 -1  0  1  2  3  4  5 
The sequence displays the negative numbers from -5 then increases by 1 to positive 5 only
```
<h2> b. x <- 1:7. What will be the value of x?</h2>
```{x}
x <- 1:7
x
The value of x is: 
1 2 3 4 5 6 7
```
<h1>2.Create a vector using seq() function</h1>
<h2>a. seq(1, 3, by=0.2) # specify step size. Write the R script and its output. Describe the output.</h2>

```{seq}   
seq(1, 3, by = 0.2) 
1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0 
It increases its value by 0.2 until it reaches its maximum value at 3
```
<h1>3.A factory has a census of its workers. There are 50 workers in total.
 
</h1> 
```
The following list shows their ages: 34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 
                                     20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24, 33, 41, 
                                     53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18
``` 
<h2>a. Access 3rd element, what is the value?</h2>
```{worker_age}   
>worker_age[3] #Its value is 22
```
<h2>b. Access 2nd and 4th element, what are the values?</h2>
```{worker_age1}
>worker_age1 <- worker_age[c(2,4)]
>worker_age1  #Its value is 28 & 36 
```
<h2>c. Access all but the 4th and 12th element is not
included. Write the R script and its output.</h2>
```{worker_age2}
> worker_age2 <- worker_age[-c(4,12)]
> worker_age2
[[1]]
[1] 34
[[2]]
[1] 28
[[3]]
[1] 22
[[4]]
[1] 27
[[5]]
[1] 18
[[6]]
[1] 52
[[7]]
[1] 39
[[8]]
[1] 42
[[9]]
[1] 29
[[10]]
[1] 35
[[11]]
[1] 27
[[12]]
[1] 22
[[13]]
[1] 37
[[14]]
[1] 34
[[15]]
[1] 19
[[16]]
[1] 20
[[17]]
[1] 57
[[18]]
[1] 49
[[19]]
[1] 50
[[20]]
[1] 37
[[21]]
[1] 46
[[22]]
[1] 25
[[23]]
[1] 17
[[24]]
[1] 37
[[25]]
[1] 43
[[26]]
[1] 53
[[27]]
[1] 41
[[28]]
[1] 51
[[29]]
[1] 35
[[30]]
[1] 24
[[31]]
[1] 33
[[32]]
[1] 41
[[33]]
[1] 53
[[34]]
[1] 40
[[35]]
[1] 18
[[36]]
[1] 44
[[37]]
[1] 38
[[38]]
[1] 41
[[39]]
[1] 48
[[40]]
[1] 27
[[41]]
[1] 39
[[42]]
[1] 19
[[43]]
[1] 30
[[44]]
[1] 61
[[45]]
[1] 54
[[46]]
[1] 58
[[47]]
[1] 26
[[48]]
[1] 18
```
<h1>4.Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the
vector, names(x).</h1> 
```{num4}
num4 <- c("first"=3, "second"=0, "third"=9)
 
```
<h2>a. The output displays only the "first" and "third" variables using array. Describe the output.</h2>
```{num4}
num4[c("first", "third")] 
num4#The output displays only the "first" and "third" variables using array.
first third 
    3     9
```
<h2>b. Write the code and its output.</h2>
```{a}
>num4 <- c("first"=3, "second"=0, "third"=9)
num4 #first second  third 
     #  3      0      9 
>num4[c("first", "third")]

num4 #first third 
     #    3     9
```
<h1>5.Create a sequence x from -3:2.</h1>
<h2>a. Modify 2nd element and change it to 0;
x[2] <- 0
x
Describe the output.</h2>
```{num}
num5[2] <- 0
num5  #The second element in the array was changed to 0 and the result is when it is sequenced, the -2 
      was changed to 0
```
<h2>b. Write the code and its output.</h2>
```{num}
num5[2] <- 0
num5
[1] -3  0 -1  0  1  2
```

<h1>6.The following data shows the diesel fuel purchased by Mr. Cruz.</h1>

<table class="round">
 
 
<table border="1">
 <tr>
<th>Month</th>
<th> Jan</th>
<th> Feb</th>
<th>March</th>
<th>Apr</th>
<th>May</th>
<th>June</th>
</tr>
<tr>
<td> Price per liter (PhP)</td>
<td> 52.50</td>
<td> 57.25</td>
<td> 60.00</td>
<td> 65.00</td>
<td> 74.25</td>
<td> 54.00</td>
</tr>
<tr>
<td>Purchase–quantity(Liters)</td>
<td>25</td>
<td>30</td>
<td>40</td>
<td>50</td>
<td>10</td>
<td>45</td>
</tr>
</table>
<h2>a. Create a data frame for month, price per liter (php)
and purchase-quantity (liter). Write the R scripts and
its output.</h2>
```{month}
>month <- c("Jan", "Feb", "March", "Apr", "May", "June")
>price_per_liter <- c(52.50,57.25,60.00,65.00,74.25,54.00)
>purchase_quantity <- c(25,30,40,50,10,45)
>data.frame <- data.frame(month,  price_per_liter,  purchase_quantity)
>data.frame
month price_per_liter purchase_quantity
1Jan           52.50                25
2Feb           57.25                30
3March         60.00                40
4Apr           65.00                50
5May           74.25                10
6June          54.00                45
```
<h2>b. What is the average fuel expenditure of Mr. Cruz from
Jan to June? Note: Use ‘weighted.mean(liter,
purchase)‘. Write the R scripts and its output.</h2>
```{weightedmean}
The avg fuel expenditure of Mr. Cruz from Jan to June is 59.2625
weighted.mean(price_per_liter,purchase_quantity)
[1] 59.2625
```
<h1>7.R has actually lots of built-in datasets. For example, the rivers data “gives the lengths
(in miles) of 141 “major” rivers in North America, as compiled by the US Geological
Survey”.</h1>
<h2>a. Type “rivers” in your R console.
Create a vector data with 7
elements, containing the number of elements (length)
in rivers, their sum (sum), mean (mean),
median(median), variance(var), standard deviation(sd),
minimum (min) and maximum (max).</h2>
```{data}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
```
<h2>b. What are the results? </h2>
```{data}
[1]141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708    135.0000   3710.0000 
```
<h2>c. Write the R scripts and its outputs.</h2>
```{data}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
          sd(rivers), min(rivers), max(rivers))
data
[1]141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708    135.0000   3710.0000
```

<h1>8.The table below gives the 25 most powerful celebrities and their annual pay as ranked
by the editions of Forbes magazine and as listed on the Forbes.com website.</h1>
 
```{power_ranking}
 power_ranking   celebtrity_name   pay
            1        Tom Cruise    67
            2     Rolling Stone    90
            3     Oprah Winfrey    225
            4                U2    110
            5       Tiger Woods    90
            6  Steven Spielberg    332
            7      Howard Stern    302
            8           50 Cent    41
            9  Cast of Sopranos    52
            10         Dan Brown   88
            11 Bruce Springsteen   55
            12      Donald Trump   44
            13      Muhammad Ali   55
            14    Paul McCartney   40
            15      George Lucas   233
            16        Elton John   34
            17   David Letterman   40
            18    Phil Mickelson   47
            19       J.K Rowling   75
            20        Bradd Pitt   25
            21     Peter Jackson   39
            22   Dr. Phil McGraw   45
            23       Jay   Lenon   32
            24       Celine Dion   40
            25       Kobe Bryant   31
```
<h2>a. Create vectors according to the above table.
Write the R scripts and its output.</h2>
```{powerRanking}
power_ranking   <- c(1:25)
celebtrity_name <- c("Tom Cruise", "Rolling Stone", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", 
                     "Howard Stern", "50 Cent", "Cast of Sopranos", "Dan Brown", "Bruce Springsteen", 
                     "Donald Trump","Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", 
                     "David Letterman","Phil Mickelson","J.K Rowling", "Bradd Pitt", "Peter Jackson", 
                     "Dr. Phil McGraw", "Jay Lenon","Celine Dion", "Kobe Bryant" )
pay             <- c(67,90,225,110,90,332,302,41,52,88,55,44,55,40,233,34,40,47,75,25,39,45,32,40,31)

```
<h2>b. Modify the power ranking and pay of J.K. Rowling.
Change power ranking to 15 and pay to 90. Write the
R scripts and its output.</h2>

```{power_ranking}
power_ranking[19] <- 15
power_ranking 
[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 15 20 21 22 23 24 25
pay[19] <- 90
pay 
[1]  67  90 225 110  90 332 302  41  52  88  55  44  55  40 233  34  40  47  90  25  39  45  32  40  31
```
<h2>c. Create an excel file from the table above and save it
as csv file(PowerRanking). Import the csv file into
the RStudio. What is the R script?</h2>
```{csvFile}
csv_file <- "PowerRanking.csv"
write.csv(PowerRanking, file = csv_file)
PowerRankingCSV <- read.csv("PowerRanking.csv")
```
<h2>d. Access the rows 10 to 20 and save it as Ranks.RData.
Write the R script and its output.</h2>
```{rankdata}

Power_Ranking <- PowerRankingCSV[10:20,]
Power_Ranking
#                        power_ranking   celebtrity_name      pay
#           10            10                 Dan Brown        88
#           11            11              Bruce Springsteen   55
#           12            12                 Donald Trump     44
#           13            13                Muhammad Ali      55
#           14            14              Paul McCartney      40
#           15            15             George Lucas        233
#           16            16               Elton John         34
#           17            17             David Letterman      40
#           18            18              Phil Mickelson      47
#           19            19               J.K Rowling        75
#           20            20                Bradd Pitt        25
save(Power_Ranking, file = "Ranks.RData")
load("Ranks.RData")
```
<h2>e. Describe its output.</h2>
```{ranksRData}
The PowerRank result was change to 10 to 20 elements.
```
<h1>9.Download the Hotels-Vienna https://tinyurl.com/Hotels-Vienna</h1>
<h2>a. Import the excel file into your RStudio.
What is the R script?</h2>
```{hotel}
library(readxl)
hotels_vienna <- read_excel("hotels-vienna.xlsx")
View(hotels_vienna)
hotels_vienna
```
<h2>b. How many dimensions does the dataset have?
What is the R script? WHat is its output?</h2>
```{dim}
dim(hotels_vienna)  
[1] 428  24
```
<h2>c. Select columns country, neighbourhood,
price, stars, accomodation_type, and
ratings. Write the R script.</h2>
```{col}
col <- colnames(hotels_vienna)
col
colnames1 <- col[c(1,6,7,8,22,24)]
colnames1 
[1] "country"            "neighbourhood"      "price"              "city"            "accommodation_type"
[6] "rating"
```
<h2>d. Save the data as **new.RData to your RStudio. Write the
R script.</h2>
```{script}
save(hotels_vienna, file = "new.RData")
new <-load("new.RData")
View(new)
```
<h2>e. Describe its output.</h2>
```{output}
head(hotels_vienna, 6) 
# country city_actual rating_count center1label center2label neighbourhood price city   stars ratingta
# <chr>   <chr>       <chr>        <chr>        <chr>        <chr>         <dbl> <chr>  <dbl> <chr>   
# 1 Austria Vienna      36           City centre  Donauturm    17. Hernals      81 Vienna     4 4.5     
# 2 Austria Vienna      189          City centre  Donauturm    17. Hernals      81 Vienna     4 3.5     
# 3 Austria Vienna      53           City centre  Donauturm    Alsergrund       85 Vienna     4 3.5     
# 4 Austria Vienna      55           City centre  Donauturm    Alsergrund       83 Vienna     3 4       
# 5 Austria Vienna      33           City centre  Donauturm    Alsergrund       82 Vienna     4 3.5     
# 6 Austria Vienna      25           City centre  Donauturm    Alsergrund      229 Vienna     5 4.5  
tail(hotels_vienna, 6L)
# 1 Austria Vienna      53           City centre  Donauturm    Wieden           73 Vienna   3   3       
# 2 Austria Vienna      2            City centre  Donauturm    Wieden          109 Vienna   3   3       
# 3 Austria Vienna      145          City centre  Donauturm    Wieden          185 Vienna   5   4       
# 4 Austria Vienna      112          City centre  Donauturm    Wieden          100 Vienna   4   4.5     
# 5 Austria Vienna      169          City centre  Donauturm    Wieden           58 Vienna   3   3       
# 6 Austria Vienna      80           City centre  Donauturm    Wieden          110 Vienna   3.5 NA   
```
<h1>10.Create a list of ten (10) vegetables you ate during your lifetime. If none, just list down.</h1>
<h2>a. Write the R scripts and its output.</h2>
```{vegetables}
vegetables <- list("cabbage", "carrot", "spinach","potato", "garlic", "corn", "onion", "tomato", "eggplant", "cucumber")
vegetables
[[1]]
[1] "cabbage"

[[2]]
[1] "carrot"

[[3]]
[1] "spinach"

[[4]]
[1] "potato"

[[5]]
[1] "garlic"

[[6]]
[1] "corn"

[[7]]
[1] "onion"

[[8]]
[1] "tomato"

[[9]]
[1] "eggplant"

[[10]]
[1] "cucumber"
```
<h2>b. Add 2 additional vegetables after the last vegetables
in the list. What is the R script and its output?</h2>
```{vegetables}
addVegetables <- c(vegetables, "mushroom", "ginger")
addVegetables 
[[1]]
[1] "cabbage"

[[2]]
[1] "carrot"

[[3]]
[1] "spinach"

[[4]]
[1] "potato"

[[5]]
[1] "garlic"

[[6]]
[1] "corn"

[[7]]
[1] "onion"

[[8]]
[1] "tomato"

[[9]]
[1] "eggplant"

[[10]]
[1] "cucumber"

[[11]]
[1] "mushroom"

[[12]]
[1] "ginger"
```
<h2>c. Add 4 additional vegetables after index 5. How many
datapoints does your vegetable list have? What is the
R script and its output?</h2>
```{vegerables}
addVegetables4 <- append(addVegetables, c("lettuce", "zucchini", "radish", "bell pepper"), after = 5)
addVegetables4
[[1]]
[1] "cabbage"

[[2]]
[1] "carrot"

[[3]]
[1] "spinach"

[[4]]
[1] "potato"

[[5]]
[1] "garlic"

[[6]]
[1] "lettuce"

[[7]]
[1] "zucchini"

[[8]]
[1] "radish"

[[9]]
[1] "bell pepper"

[[10]]
[1] "corn"

[[11]]
[1] "onion"

[[12]]
[1] "tomato"

[[13]]
[1] "eggplant"

[[14]]
[1] "cucumber"

[[15]]
[1] "mushroom"

[[16]]
[1] "ginger"
num_vegetables <- length(addVegetables4)
num_vegetables 
[1] 16
```
<h2>d. Remove the vegetables in index 5, 10, and 15. How
many vegetables were left? Write the codes and its
output.</h2>
```{vegetables}
ddVegetables5 <- addVegetables4[-c(5,10,15)]
addVegetables5 
[[1]]
[1] "cabbage"

[[2]]
[1] "carrot"

[[3]]
[1] "spinach"

[[4]]
[1] "potato"

[[5]]
[1] "lettuce"

[[6]]
[1] "zucchini"

[[7]]
[1] "radish"

[[8]]
[1] "bell pepper"

[[9]]
[1] "onion"

[[10]]
[1] "tomato"

[[11]]
[1] "eggplant"

[[12]]
[1] "cucumber"

[[13]]
[1] "ginger"
num_addVegetables5 <- length(addVegetables5)
num_addVegetables5 
[1] 13
```

</body>

</html>
